### ISSUE TITLE
It doesn't throw exception when error occurs

### ISSUE THREAD

**Issue by wejick** [weisslj/cpp-optparse#2]
On OptionParser::error would immediately exit program after printing help message.
I think exiting from library is not good, let alone main loop to decide what to do after error. So I would like to see cpp-optparse throw an exception instead exit after error.

*I am at the middle of nowhere which doesn't allow me to create pull request

**Comment by weisslj** [comment]
Thanks for reporting this and sorry for not replying for such a long time! @mpherg implemented this in pull request #6. The reason for `std::exit` was compatibility with the Python implementation.
