### ISSUE TITLE
OptParse ignores defaults set within an OptionGroup

### ISSUE THREAD

**Issue by bnbowman** [weisslj/cpp-optparse#3]
OptionParser.set_defaults() works, since that is set at the scope of the main parser, but OptionGroup.set_deaults() and Option.set_default() don't.

add_option_group() only adds options to "_optmap_s" and "_optmap_l" of the parent parser, while parse_args() iterates over "_defaults" and "_opts" to set defaults, so the defaults are never called

**Comment by weisslj** [comment]
Thanks for the report! This got fixed in 881f360, 89762d8, and 1f6c809. The last commit removes `OptionGroup.set_deaults()`, which does not exist in Python.
